# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 23:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_blargh'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BLARGH',
        ),
    ]
